-- chaoxing 题库种子（无事务包裹，D1 整体执行）
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('教育是民族振兴、社会进步的基石。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('构建人类命运共同体，就是为了造福各国人民，促进世界和平，实现共同繁荣和发展。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('历史充分证明，没有中国共产党，就没有新中国，就没有中华民族伟大复兴，历史和人民选择了中国共产党。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全人类共同价值与西方所谓的“普世价值”是两个不同的概念，两者存在根本区别。前者反映了全人类的共同利益，体现了不同文明的价值共识，后者仅代表部分西方国家的利益，依靠霸权强行输出。世界上不存在高人一等的“自由民主”，不存在唯我独尊的“普世价值”。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国社会主要矛盾的变化改变了我国社会主义所处的历史阶段。', 'A. 对 B. 错', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('实体经济是一国经济的立身之本、财富之源，是构筑未来发展战略优势的重要支撑。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持党的全面领导，可以把党的领导与依法治国对立起来。', 'A. 对 B. 错', '错误');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('关键核心技术可以通过购买使用，不必掌握在自己手中。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('法治可以脱离一定社会经济、政治和文化所提供的社会条件。', 'A. 对 B. 错', '错误');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义道路是中国共产党领导人民在改革开放后才探索出来的。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('台湾问题因民族弱乱而产生，必将随着民族复兴而解决. 台湾前途在于国家统一，台湾同胞福祉系于民族复兴。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义，既坚持了科学社会主义基本原则，又根据时代条件赋予其鲜明的中国特色。这就是说，中国特色社会主义是社会主义，不是别的什么主义。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设教育强国是一项复杂的系统工程，需要紧紧围绕立德树人这个根本任务，着眼于培养德智体美劳全面发展的社会主义建设者和接班人。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“一国” 是实行 “两制” 的前提和基础，两制从属并统一于一国之内。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('办好中国的事情，关键在人民，与党的领导没有必然联系。', 'A. 对 B. 错', '错误');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('人民民主是社会主义的生命，没有民主就没有社会主义。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('做统战工作要把握好固守圆心和扩大共识、潜绩和显绩、原则性和灵活性、团结和斗争的关系。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('科技创新是百年未有之大变局中的一个关键变量，世界主要国家纷纷把科技创新作为国际战略博弈的主要战场。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设社会主义文化强国、推动社会主义文化繁荣兴盛，关键在于坚定中国特色社会主义文化自信。', 'A. 对 B. 错', '正确');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('在“一国两制”之下，作为直辖于中央人民政府的香港、澳门特别行政区，享有高度自治权，包括（ ）。', 'A. 行政管理权 B. 立法权 C. 独立的司法权和终审权 D. 外交权', 'A. 行政管理权 B. 立法权 C. 独立的司法权和终审权');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代中国正处于中华民族伟大复兴的关键时期，因为（ ）。', 'A. 我国发展站在了新的历史起点上 B. 改革面临着许多前所未有的困难和挑战，处于攻坚克难的关键时期 C. 新时代的中国发生新的历史性变革 D. 中国式现代化全面推进拓展', 'B. 改革面临着许多前所未有的困难和挑战，处于攻坚克难的关键时期');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('铸牢中华民族共同体意识，就是要引导各族人民牢固树立（ ）的共同体理念。', 'A. 休戚与共 B. 荣辱与共 C. 生死与共 D. 命运与共', 'A. 休戚与共 B. 荣辱与共 C. 生死与共 D. 命运与共');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('对中央全面管治权和特别行政区高度自治权的正确理解是（ ）。', 'A. 中央对包括香港、澳门特别行政区在内的所有地方行政区域拥有全面管治权 B. 全面管治权是授权特别行政区高度自治的前提和基础，高度自治权是中央行使全面管治权的体现 C. 它们之间是源与流、本与末的关系 D. 高度自治不是完全自治，而是中央授予的地方事务管理权，中央有权对特别行政区高度自治权行使情况进行监督', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面地理解和把握新发展理念，（ ）。', 'A. 要从根本宗旨上把握新发展理念，坚持以人民为中心的发展思想 B. 要从问题导向上把握新发展理念，切实解决发展不平衡不充分问题 C. 要从忧患意识上把握新发展理念，下好先手棋，打好主动仗 D. 新发展理念是引领我国发展全局深刻变革的科学指引', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党依靠人民，推进（ ）走出一条中国特色社会主义道路。', 'A. 改革开放 B. 社会主义现代化建设 C. 全面建成小康社会 D. 社会主义现代化国家', 'A. 改革开放');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国式现代化是中国共产党领导的社会主义现代化，这是对中国式现代化的定性，是（ ）的。', 'A. 管总 B. 管根本 C. 管长远 D. 管大局', 'ABC');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想是“两个结合”的重大成果。那么“两个结合”是指马克思主义基本原理同（ ）的结合。', 'A. 中国具体实际 B. 中华优秀传统文化 C. 中国人民 D. D.中国共产党', 'A. 中国具体实际 B. 中华优秀传统文化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持中国特色社会主义文化建设的“二为”方向，“二为”是（ ）。', 'A. 为中国共产党治国理政服务 B. 为建设社会主义现代化国家 C. 为人民服务 D. 为社会主义服务', 'C. 为人民服务 D. 为社会主义服务');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('必须坚持中国特色社会主义文化发展道路，增强文化自信，必须（ ）。', 'A. 围绕举旗帜、聚民心、育新人、兴文化、展形象建设社会主义文化强国 B. 发展面向现代化、面向世界、面向未来的，民族的科学的大众的社会主义文化 C. 激发全民族文化创新创造活力，增强实现中华民族伟大复兴的精神力量 D. 以马克思主义为指导，坚守中华文化立场', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('关于中国梦的内涵理解正确的是（ ）。', 'A. 核心内容是国家富强、民族振兴、人民幸福 B. 中国梦是国家的梦、民族的梦、归根到底是人民的梦 C. 国家富强、民族振兴是人民幸福的基础和保障 D. 人民幸福是国家富强、民族振兴的根本出发点和落脚点', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新的征程上，开创国防和军队现代化新局面，必须全面推进（ ）， 加快把人民军队建设成为世界一流军队。', 'A. 政治建军 B. 改革强军 C. 科技强军、人才强军 D. 依法治军', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国倡导的新安全观是（ ）。', 'A. 共同、综合、合作、可持续 B. 以安全求发展 C. 结盟对抗 D. 单边安全', 'A. 共同、综合、合作、可持续');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）就是党的形象，关系人心向背，关系党的生死存亡。', 'A. 廉政教育 B. 党的作风 C. 党的思想建设 D. 党的组织建设', 'B. 党的作风');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国是工人阶级领导的、以工农联盟为基础的（ ）的社会主义国家，国家一切权力属于人民。', 'A. 人民民主专政 B. 人民当家作主 C. 中国共产党领导 D. 民主专政', 'A. 人民民主专政');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('摆脱贫困一直是困扰全球发展和治理的突出难题，我国提前（ ）实现联合国 2030 年可持续发展议程减贫目标。', 'A. 10 年 B. 15 年 C. 20 年 D. 25 年', 'A. 10 年');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义制度是一个严密完整的制度体系，起四梁八柱作用的是根本制度、基本制度、重要制度，其中具有统领地位的是（ ）。', 'A. 国家监察制度 B. 人民代表大会制度 C. 党的领导制度 D. 协商民主制度', 'C. 党的领导制度');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('为推进新时代中国特色社会主义事业提供了政治保证的是（ ）。', 'A. 全国一盘棋 B. 坚持和加强党的全面领导 C. 人民当家作主 D. 以人民为中心', 'B. 坚持和加强党的全面领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('台湾问题的性质，从根本上说是中国的（ ）。', 'A. 外交问题 B. 内政问题 C. 国际安全问题 D. 经贸问题', 'B. 内政问题');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是我国安身立命之所、发展繁荣之基。', 'A. 发展中国家 B. 周边 C. 金砖国家 D. 亚洲', 'D. 亚洲');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党中央从制定和落实中央八项规定开局破题，牢牢抓住（ ）。', 'A. “关键少数” B. “绝大多数” C. 领导干部 D. 知识分子', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('2025年5月发布的《新时代的中国国家安全》白皮书指出，“要增强忧患意识，树牢底线思维，突出重点，精准施策，有效防范化解影响我国现代化进程的重大风险”。以下对底线思维理解正确的是（ ）。', 'A. 以“守底线”取代“谋发展”，将全部治理资源集中于风险防范 B. 全面排查各类风险，重点防控可能迟滞或中断中华民族伟大复兴进程的全局性风险 C. 优先消除所有“黑天鹅”事件，确保绝对安全后再推进发展 D. 将底线思维等同于极限思维，要求在任何极端条件下都不计成本维持现状', 'B. 全面排查各类风险，重点防控可能迟滞或中断中华民族伟大复兴进程的全局性风险');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('把（ ）体系纳入中国特色社会主义法治体系，是我国法治区别于其他国家法治的鲜明特征。', 'A. 党内法规 B. 法治监督 C. 法治保障 D. 法治实施', 'A. 党内法规');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色大国外交要坚持以（ ）为根本增强战略自信。', 'A. 中国特色社会主义 B. 相互尊重、合作共赢 C. 公平正义 D. 当对对外工作的集中统一领导', 'A. 中国特色社会主义');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('法律规范体系是以（ ）为核心，由部门齐全、结构严谨、内部协调、体例科学、调整有效的法律规范所构成的有机整体。', 'A. 民法 B. 刑法 C. 宪法 D. 行政诉讼法', 'C. 宪法');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('邓小平指出：“社会主义最大的优越性就是（ ），这是体现社会主义本质的一个东西。”', 'A. 党的领导 B. 共同富裕 C. 办事效率高 D. 走和平发展道路', 'B. 共同富裕');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代十年社会建设的主要成就中，劳动年龄人口平均受教育年限（ ）。', 'A. 达到10.9年 B. 不足9年 C. 不足8年 D. 达到15年', 'A. 达到10.9年');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('湿地的生态功能不包括（ ）。', 'A. 调节气候 B. 美化环境 C. 提供工业原料 D. 维持生物多样性', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('在总体国家安全观的五大要素中，强调以（ ）为依托，推动树立共同、综合、合作、可持续的全球安全观。', 'A. 巩固国防和强大军队 B. 促进国际安全 C. 深化全球治理合作 D. 维护大国战略平衡', 'B. 促进国际安全');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是法治建设的目标。', 'A. 法治国家 B. 法治政府 C. 法治社会 D. 法治体系', 'A. 法治国家');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是党的基础性建设。', 'A. 政治建设 B. 思想建设 C. 制度建设 D. 作风建设', 'B. 思想建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('社区社会治理成效很大程度取决于（ ）能力和水平。', 'A. 市域社会治理 B. 改善人民生活 C. 基层党组织 D. 政府机构', 'C. 基层党组织');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是一个政党观察、认识、处理政治问题的立足点，反映了这个政党的世界观、方法论和执政理念，体现了这个政党的根本属性。', 'A. 人民立场 B. 政治立场 C. 社会立场 D. 党性立场', 'A. 人民立场');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国共产党区别于其他政党的显著标志是（ ）。', 'A. 深化改革 B. 人民立场 C. 促进高质量发展 D. 实事求是', 'B. 人民立场');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('毛泽东领导的“三湾改编”确立了（ ）的制度，使党的领导直达基层。', 'A. 支部建在排上 B. 支部建在连上 C. 支部建在营上 D. 支部建在团上', 'B. 支部建在连上');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代我国社会主要矛盾的变化，是在社会主义初级阶段中发生的变化，（ ）对我国社会主义所处历史阶段的判断。', 'A. 正在进行 B. 未能进行 C. 已经改变 D. 没有改变', 'D. 没有改变');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('走中国特色社会主义政治发展道路，最根本的是（ ）。', 'A. 坚持社会主义道路 B. 坚持人民当家作主 C. 坚持社会主义法治 D. 坚持党的领导', 'D. 坚持党的领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是我们党区别于其他政党的显著标志。', 'A. 勇于自我革命 B. 勇于创新 C. 勇于挑战 D. 勇于突破', 'A. 勇于自我革命');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国式现代化是造福人民的现代化，要求把不断（ ）放在更加突出的位置。', 'A. 坚定社会主义制度 B. 推进社会主义发展 C. 增进民生福祉 D. 坚持人民主体地位', 'C. 增进民生福祉');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想的重要实践要求是（ ）。', 'A. 人民至上 B. 自信自立 C. 守正创新 D. 问题导向', 'C. 守正创新');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('要坚持把（ ）放在首位、社会效益和经济效益相统一，深化文化体制改革，完善文化经济政策，不断扩大优质文化产品供给。', 'A. 经济效益 B. 社会效益 C. 文化效益 D. 政治效益', 'B. 社会效益');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('生态修复的主要手段不包括（ ）。', 'A. 围湖造田 B. 退耕还湖 C. 治理水污染 D. 种植水生植物', 'A. 围湖造田');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国宪法规定:“中华人民共和国实行依法治国，建设社会主义法治国家。”（ ）是依法治国的前提。', 'A. 建立科学完备的法律体系 B. 国家行政机关依法行政 C. 司法机关公正司法.严格执法 D. 加强法制教育，增强法制观念', 'A. 建立科学完备的法律体系');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平总书记强调，要“坚持统筹维护和塑造国家安全”。关于“塑造国家安全”，下列理解正确的是（ ）。', 'A. 塑造国家安全是更高层次、更具前瞻性的维护，侧重于通过参与全球治理、推动规则制定，主动营造于我有利的外部安全环境 B. 塑造国家安全是维护国家安全的基石，其首要任务是加强国内安全制度体系建设，筑牢内部安全防线 C. 塑造国家安全的核心在于提高防范化解重大风险的能力，确保各类风险挑战被化解在萌芽状态 D. 塑造国家安全与维护国家安全是同一概念的不同表述，二者没有本质区别，均强调内外兼顾', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('要坚持把马克思主义基本原理同中华优秀传统文化相结合，推动（ ）创造性转化、创新性发展，让中华文明展现出永久魅力和时代风采。', 'A. 中华优秀传统文化 B. 社会主义先进文化 C. 革命文化 D. 中国特色社会主义文化', 'A. 中华优秀传统文化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“天地与我并生，而万物与我为一”的“天人合一”思想，代表着我们祖先对处理（ ）的关系的重要认识。', 'A. 天与地 B. 人与自然 C. 人与社会 D. 人与人', 'B. 人与自然');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('社会主义的本质要求，中国式现代化的重要特征是（ ）。', 'A. 社会和谐 B. 共同富裕 C. 人民当家作主 D. 公平正义', 'B. 共同富裕');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平强调:“没有高度的文化自信，没有文化的繁荣兴盛，就没有中华民族伟大复兴。”我们坚定文化自信的深厚基础是（ ）。', 'A. 社会主义先进文化 B. 新民主主义文化 C. 中华优秀传统文化 D. 党和人民创造的革命文化', 'C. 中华优秀传统文化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('聚焦保障人民安宁，坚持以（ ）为导向，更快破大案、更多破小案、更准办好案、更好控发案，切实保护人民群众人身权、财产权、人格权。', 'A. 社会稳定 B. 安居乐业 C. 群众期盼 D. 安全保障', 'C. 群众期盼');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('统战工作的本质要求是（ ），解决的就是人心和力量问题。', 'A. 社会主义发展 B. 人民民主 C. 大团结大联合 D. 全过程人民民主', 'C. 大团结大联合');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('军队是要准备打仗的，一切工作都必须坚持（ ）标准，向能打仗、打胜仗聚焦。', 'A. 战斗力 B. 斗争力 C. 战争力 D. 硬实力', 'A. 战斗力');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ），这是实现祖国统一的战略支撑。', 'A. 坚持党中央对对台工作的集中统一领导 B. 坚持绝不承诺放弃使用武力 C. 坚持团结台湾同胞、争取台湾民心 D. 坚持粉碎“台独”分裂图谋', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）强调“统筹发展和安全”，并将其写入党章。', 'A. 党的十八届四中全会 B. 党的十九大 C. 党的十九届六中全会 D. 党的二十大', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义道路是（ ）。', 'A. 实现途径 B. 行动指南 C. 根本保障 D. 精神力量', 'A. 实现途径');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ），是我们党根据时代发展潮流和我国根本利益作出的战略抉择，是新时代中国外交的基本原则。', 'A. 坚持以人民为中心 B. 坚持合作共赢 C. 构建人类命运共同体 D. 坚持走和平发展道路', 'D. 坚持走和平发展道路');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('自然保护区的主要作用，不包括（ ）。', 'A. 提供木材等经济资源 B. 保护生物多样性 C. 开展科学研究 D. 进行生态教育', 'A. 提供木材等经济资源');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是国家安全的根本。', 'A. 人民安全 B. 政治安全 C. 经济安全 D. 军事安全', 'B. 政治安全');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是国家治理的基石，城乡社区是社会治理最基本的单元，是党和政府联系、服务居民群众的“最后一公里”。', 'A. 改善民生 B. 人民当家作主 C. 基层治理 D. 为人民服务', 'C. 基层治理');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是民生之源，是改善民生、实现发展成果由人民共享最重要最直接的方式。', 'A. 收入分配 B. 分配制度 C. 社会保障 D. 生活幸福', 'A. 收入分配');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是促进共同富裕的基础性制度。', 'A. 分配制度 B. 按劳分配为主体，多种分配方式并存 C. 公有制为主体、多种所有制经济共同发展 D. 初次分配、再分配、第三次分配协调机制', 'B. 按劳分配为主体，多种分配方式并存');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('人民军队永远是战斗队，人民军队的生命力在于（ ）。', 'A. 斗争力 B. 战争力 C. 战斗力 D. 硬实力', 'C. 战斗力');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国党和政府解决台湾问题的基本方针（ ）。', 'A. 中国政府承诺不以武力解决 B. 和平统一，一国两制 C. 台湾享有完全的自治权 D. 与美国等有关国家共同协商解决', 'B. 和平统一，一国两制');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面依法治国，必须始终坚持正确方向，坚定不移走（ ）。', 'A. 中国特色社会主义发展道路 B. 中国特色社会主义法治道路 C. 社会主义道路 D. 全面依法治国治国的唯一正确道路', 'B. 中国特色社会主义法治道路');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是中国特色社会主义的本质要求和重要保障。', 'A. 全面建设社会主义现代化国家 B. 全面依法治国 C. 全面深化改革 D. 全面从严治党', 'B. 全面依法治国');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代要坚持以人民为中心，在推动社会全面进步中促进（ ）的全面发展。', 'A. 人 B. 经济 C. 政治 D. 文化', 'A. 人');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('2026年4月15日是第十一个全民国家安全教育日，其活动主题是（ ）。', 'A. 贯彻落实保密法，你我都是护密人 B. 总体国家安全观·创新引领10周年 C. 统筹发展和安全，护航“十五五”新征程 D. 树牢总体国家安全观，感悟新时代国家安全成就', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ），是当代中国共产党人回答和解决关乎人类前途命运的时代之问的中国方案，是应对人类共同挑战、建设更加繁荣美好世界的人间正道，也是新时代对外工作的总目标。', 'A. 一带一路 B. 推动构建人类命运共同体 C. 美丽世界 D. 合作共赢', 'B. 推动构建人类命运共同体');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('各级各类教育的生命线是（ ）。', 'A. 高质量发展 B. 立德树人 C. 教育优先发展 D. 人民满意', 'B. 立德树人');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('将坚持马克思主义在意识形态领域指导地位确立为我们必须遵循的根本制度的会议是（ ）。', 'A. 十九届二中全会 B. 十九届三中全会 C. 十九届四中全会 D. 十九届五中全会', 'C. 十九届四中全会');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('决胜全面建成小康社会的三大攻坚战是防范化解重大风险、精准脱贫、（ ）。', 'A. 加强民生保障 B. 推动高质量发展 C. 污染防治 D. 实现乡村全面振兴', 'C. 污染防治');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是最基本的民生，是劳动者赖以生存和发展的基础、共享经济发展成果的基本条件，关系到亿万劳动者及其家庭的切身利益。', 'A. 社会保障 B. 教育 C. 就业 D. 医疗', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('特别行政区的高度自治权来源于（ ）。', 'A. 地方自主争取 B. 中央授权 C. 国际承认 D. 民众选举', 'B. 中央授权');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国经济发展进入新常态后，经济增长速度的变化趋势是（ ）。', 'A. 从低速转向高速 B. 从高速转向中高速 C. 从匀速转向变速 D. 始终保持高速增长', 'B. 从高速转向中高速');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）提出坚持和完善共建共治共享的社会治理制度，体现了我们党对社会运行和社会治理规律认识的深化。', 'A. 党的十八大 B. 党的十九大 C. 党的十九届四中全会 D. 党的二十大', 'C. 党的十九届四中全会');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('以下哪项是推动绿色高质量发展的重要举措（ ）。', 'A. 加大化石能源开采 B. 推进碳达峰碳中和 C. 扩大高污染产业规模 D. 减少环保投入', 'B. 推进碳达峰碳中和');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('世界未有之大变局正在加速演变。（ ）仍然是时代主题，但是不稳定不确定性更加突出。', 'A. 发展与共享 B. 和平与融合 C. 和平与发展 D. 开放与包容', 'C. 和平与发展');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的（ ）是划时代的，实现了改革开放由局部探索、破冰突围到系统集成、全面深化的转变，开创了改革开放新局面。', 'A. 十一届三中全会 B. 十八大 C. 十八届三中全会 D. 二十大', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持和加强党的全面领导，必须健全党( )的领导体制机制。', 'A. 对人大、政府、政协等 B. 仅对军队 C. 仅对国有企业 D. 仅对意识形态领域', 'A. 对人大、政府、政协等');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是担负文化使命、实现中华民族伟大复兴的根本保证。', 'A. 党的领导 B. 文化发展繁荣 C. 文化自信 D. 科学的民族的大众的文化', 'A. 党的领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('培养人才是国家和民族长远发展大计。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持党的全面领导，要弱化党中央集中统一领导，充分下放地方自主权限。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('市场在资源配置中起辅助性作用，政府起决定性作用。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('2014年4月10日，习近平总书记在中央国家安全委员会第二次会议上创造性提出总体国家安全观，强调必须坚持总体国家安全观，走出一条中国特色国家安全道路。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“四个全面”战略布局中，全面深化改革是战略目标。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面从严治党的核心是加强党的领导，基础在全面，关键在严，要害在治。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('共同富裕是中国特色社会主义的本质要求，我国很快就实现共同富裕。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的政治建设的首要任务是保证全党服从中央，坚持党中央权威和集中统一领导。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持以人民为中心，要把个人政绩放在人民利益前面。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('巩固提高一体化国家战略体系和能力，关键是要实现军政军民团结。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义坚持了科学社会主义的基本原则，同时结合了中国实际。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('对香港、澳门来说，“一国两制”是最大的优势，国家改革开放是最大的舞台，共建“一带一路”、粤港澳大湾区建设等国家战略实施是新的重大机遇。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('发展和安全是一体之两翼、驱动之双轮。发展是安全的条件，安全是发展的基础和目的，发展和安全要同步推进。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('推进社会治理现代化的目标是建设人人有责、人人尽责、人人享有的社会治理共同体。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义进入新时代，意味着我国已经成为发达国家。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面依法治国，必须加快完善中国特色社会主义法律体系，使之更加科学完备、统一权威。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('改革是中国特色社会主义发展的根本动力，改革开放只有进行时、没有完成时。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义是中国共产党和中国人民在长期实践中得出的必然结论。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国共产党领导是中国特色社会主义最本质的特征，（ ）。', 'A. 这是在近代以来中国历史发展中形成的 B. 这是由中国最广大人民根本利益决定的 C. 这是实现中华民族伟大复兴历史任务决定的 D. 这决定了中国特色社会主义其他特点和特征', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('1921年中国共产党的诞生，是一件开天辟地的大事变，它深刻改变了（ ）。', 'A. 近代以后中华民族发展的方向和进程 B. 中国人民和中华民族的前途和命运 C. 世界发展的趋势和格局 D. 人类社会的发展规律', 'A、B、C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国基层民主有多种多样的形式，如（ ）。', 'A. 以村民委员会为组织形态的农村村民自治 B. 以社区居民委员会为组织形态的城市居民自治 C. 以职工代表大会为组织依托的企事业单位职工自治 D. 以上都对', 'D. 以上都对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('不断创新社会治理方式，要做到（ ）。', 'A. 正确处理好维稳与维权、活力与秩序的关系 B. 运用法治思维和法治方式统筹社会力量、平衡社会利益、调节社会关系 C. 强化互联网思维，推进政府决策科学化、社会治理精准化、公共服务高效化 D. 坚持系统思维，综合运用专业化工作方法提升社会治理效能', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('深化国防和军队改革，要（ ）。', 'A. 按照军委管总、战区主战、军种主建的总原则改革领导指挥体制 B. 推进军队规模结构和力量编成改革，构建中国特色现代军事力量体系 C. 深化军队党的建设制度改革、创新军事力量运用政策制度；重塑军事力量建设政策制度、改革军事管理政策制度 D. 建立健全中国特色社会主义军事政策制度体系', 'A. 按照军委管总、战区主战、军种主建的总原则改革领导指挥体制');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的领导是全面的，主要表现在（ ）。', 'A. 领导对象 B. 领导内容 C. 领导过程 D. 领导方式', 'A. 领导对象B. 领导内容C. 领导过程D. 领导方式');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“邦国虽有良法，要是人民不能全都遵守，仍不能实现法治。”亚里士多德的名言启示我们，全面推进依法治国必须（ ）。', 'A. 民主立法，保障公民的权益都得到法律的确认 B. 广泛凝聚社会共识，尽快建立完备的法律体系 C. 开展法治宣传教育，促进全社会树立法治意识 D. 崇尚法治，推动全民依法行使权利和履行义务', 'C. 开展法治宣传教育，促进全社会树立法治意识');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面深化改革开放，是一场全面、系统、整体的制度创新，要着眼于建立一整套更完备、更稳定、更管用的制度体系，包括（ ）。', 'A. 坚持和完善人民当家作主制度体系 B. 完善涉外经济法律和规则体系 C. 坚持和完善繁荣发展社会主义先进文化的制度，坚持和完善生态文明制度体系 D. 坚持和完善统筹城乡的民生保障制度和共建共治共享的社会治理制度', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('要坚持开放和安全的有机统筹，在保障安全中持续扩大开放，着力增强（ ），创造有利于我国经济社会发展的安全环境，牢固树立开放型经济安全防线。', 'A. 经济发展能力 B. 自身竞争能力 C. 开放监管能力 D. 风险防控能力', 'BCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('深化供给侧结构性改革这条主线，要发挥创新第一动力作用，持续推动（ ），着力突破供给约束堵点，以自主可控、优质有效的供给满足和创造需求。', 'A. 科技创新 B. 制度创新 C. 文化创新 D. 理论创新', 'A. 科技创新');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('大自然是人类赖以生存发展的基本条件，（ ）是全面建设社会主义现代化国家的内在要求。', 'A. 尊重自然 B. 顺应自然 C. 融入自然 D. 保护自然', 'ABD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国独立自主的和平外交政策的内容包括（ ）。', 'A. 中国始终根据事情本身的是非曲直决定自己的立场和政策 B. 中国尊重各国主权和领土完整，尊重各国人民选择的发展道路和社会制度 C. 坚决反对一切形式的範权主义和强权政治；反对冷战思维，反对干涉别国内政，反对搞双重标准 D. 奉行防御性的国防政策，中国永远不称霸、永远不搞扩张', 'A、B、C、D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('关乎党和国家前途命运、党和人民事业成败的根本性问题是（ ）。', 'A. 强大的武装力量 B. 庞大的组织人数 C. 坚强的领导核心 D. 科学的理论指导', 'C. 坚强的领导核心');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持把马克思主义基本原理同（ ）相结合，用马克思主义观察时代、把握时代、引领时代，继续发展当代中国马克思主义、21世纪马克思主义。', 'A. 中国具体实际相结合 B. 中华优秀传统文化 C. 中国精神 D. 民族特色', 'AB');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是社会主义的本质要求，是中国式现代化的重要特征。', 'A. 共同富裕 B. 全面小康 C. 建设工业强国 D. 建设创新型国家', 'A. 共同富裕');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）就是要按照时代特点和要求，对那些至今仍有借鉴价值的内涵和陈旧的表现形式加以改造，赋予其新的时代内涵和现代表达形式，激活其生命力。', 'A. 创新性发展 B. 保护好、传承好文化遗产 C. 繁荣发展文化事业和文化产业 D. 创造性转化', 'D. 创造性转化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是当代中国发展进步的根本制度保障，具有明显制度优势。', 'A. 中国特色社会主义制度 B. 中国特色社会主义经济制度 C. 中国特色社会主义理论体系 D. 中国特色社会主义道路', 'A. 中国特色社会主义制度');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代中国外交的基本原则是（ ）。', 'A. 坚持走特色外交道路 B. 坚持走和平发展道路 C. 坚持走合作共赢道路 D. 坚持走开放包容道路', 'B. 坚持走和平发展道路');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('就业是最大的民生，其根本保障在于（ ）。', 'A. 发展实体经济 B. 扩大公务员岗位 C. 鼓励灵活就业 D. 提高最低工资标准', 'A. 发展实体经济');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的十八大以来，以习近平同志为核心的党中央高度重视民生问题，注重加强普惠性、基础性、兜底性民生建设，坚决打赢脱贫攻坚战，着力解决人民群众急难愁盼问题，扎实推进共同富裕，不断增强人民（ ）。', 'A. 获得感、幸福感、安全感 B. 幸福感、安全感、获得感 C. 幸福感、满足感、安全感 D. 获得感、满足感、安全感', 'A. 获得感、幸福感、安全感');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('推进中国式现代化必须牢牢把握的重大原则包括：坚持和加强党的全面领导、坚持中国特色社会主义道路、坚持以人民为中心的发展思想、坚持深化改革开放、（ ）。', 'A. 坚持发扬斗争精神 B. 坚持高质量发展 C. 坚持系统观念 D. 坚持独立自主', 'A. 坚持发扬斗争精神');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('至2021年，我国中等收入人群规模超过（ ）。', 'A. 14亿 B. 13亿 C. 10亿 D. 4亿', 'D. 4亿');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('落实立德树人根本任务的关键课程是（ ）。', 'A. 基础文化理论课 B. 劳动技术教育课 C. 思想政治理论课 D. 社会公德教育课', 'C. 思想政治理论课');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平指出:“我们党作为世界（ ）大党，没有什么外力能够打倒我们，能够打倒我们的只有我们自己。”', 'A. 第一 B. 第二 C. 第三 D. 第四', 'A. 第一');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）提出创新社会治理体制，从“社会管理”到“社会治理”，虽然只是一字之差，却意味着社会建设理念、体制和方式的重大变革。', 'A. 党的十八大 B. 党的十八届三中全会 C. 党的十九届六中全会 D. 党的二十大', 'B. 党的十八届三中全会');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('下列不属于百年未有之大变局的表现是（ ）。', 'A. 国际力量对比深刻调整 B. 西方国家主导的经济政治秩序逐渐成形 C. 新一轮科技革命和产业变革深入发展 D. 国际体系和国际秩序深度调整', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是一个国家、一个民族的灵魂。', 'A. 经济 B. 政治 C. 文化 D. 宗教', 'C. 文化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('高质量发展是全面建设社会主义现代化国家的（ ）。', 'A. 根本保证 B. 首要任务 C. 制度基础 D. 战略基点', 'B. 首要任务');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中华民族的文化主体性最有力的体现是（ ）。', 'A. 邓小平理论 B. “三个代表”重要思想 C. 科学发展观 D. 习近平新时代中国特色社会主义思想', 'D. 习近平新时代中国特色社会主义思想');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的（ ）是党的事业的骨干，是人民的公仆，是全面从严治党的重点对象。', 'A. 领导干部 B. 全体党员 C. 高级干部 D. 基层干部', 'A. 领导干部');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设（ ）的世界，就要坚持交流互鉴，促进和而不同、兼收并蓄的文明交流，不同文明之间要对话不要对立，要交流不要取代，要包容不要冲突，推动人类文明实现创造性发展。', 'A. 持久和平 B. 开放包容 C. 普遍安全 D. 共同繁荣', 'B. 开放包容');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持以（ ）为理念引领全球治理体系改革。', 'A. 公平正义 B. 集体安全 C. 绿色发展 D. 高质量发展', 'A. 公平正义');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持党要管党、全面从严治党，以党的（ ）为统领。', 'A. 政治建设 B. 思想建设 C. 组织建设 D. 作风建设', 'A. 政治建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）就是要坚定理想信念宗旨，自觉抵御各种腐朽思想侵蚀，提高政治免疫力，清除一切侵蚀党的健康肌体的病毒。', 'A. 自我净化 B. 自我完善 C. 自我革新 D. 自我提高', 'A. 自我净化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('保持香港、澳门长期繁荣稳定，必须坚持以（ ）为核心的行政主导体制。', 'A. 立法会 B. 司法机关 C. 行政长官 D. 中央驻港机构', 'C. 行政长官');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代十年社会建设的主要成就中，居民人均可支配收入从2012的1.65万元，增加到2021年的（ ）。', 'A. 超过10万元 B. 超过8万元 C. 超过6万元 D. 超过3.5万元', 'D. 超过3.5万元');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是当代中国文化发展的灵魂。', 'A. 社会主义 B. 马克思主义 C. 中国特色社会主义 D. 中华优秀传统文化', 'B. 马克思主义');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）与人民群众切身利益关系最密切，是人民群众安全感的晴雨表，是社会安定的风向标。', 'A. 政治安全 B. 经济安全 C. 社会安全 D. 文化安全', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('在推动高质量发展过程中，建设现代化产业体系的重点是（ ）。', 'A. 淘汰传统产业 B. 发展高端制造业 C. 限制服务业发展 D. 只发展新兴产业', 'B. 发展高端制造业');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('水污染治理的主要措施不包括（ ）。', 'A. 加强工业废水处理 B. 减少农业面源污染 C. 增加污水排放口 D. 建设污水处理厂', 'C. 增加污水排放口');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是国家经济社会发展的支撑力量，在国家发展中具有基础性、先导性、全局性地位。', 'A. 教育 B. 科技 C. 人才 D. 创新', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国秉持的周边外交理念是（ ）。', 'A. 利益融合 B. 互利合作 C. 友好互信 D. 亲诚惠容', 'D. 亲诚惠容');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国提出的 “双碳” 目标是指（ ）。', 'A. 碳达标、碳清零 B. 碳达峰、碳中和 C. 碳排放、碳吸收 D. 碳交易、碳储备', 'B. 碳达峰、碳中和');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('在新时代的强军目标中，（ ）是核心。', 'A. 听党指挥 B. 能打胜仗 C. 作风优良 D. 全面建成世界一流军队', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是核心战斗力，是军事发展中最活跃、最具革命性的因素。', 'A. 改革 B. 科技 C. 人才 D. 武器装备', 'B. 科技');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是运用国家制度管理国家各方面事务的能力。', 'A. 执政能力 B. 国家治理能力 C. 现代化建设能力 D. 政治执行力', 'B. 国家治理能力');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('国家宪法日是 （ ）。', 'A. 12月4日 B. 12月5日 C. 12月3日 D. 12月1日', 'A. 12月4日');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('经过不懈努力，党找到了（ ）这一跳出治乱兴衰历史周期率的第二个答案，确保党永远不变质、不变色、不变味。', 'A. 新发展理念 B. 自我革命 C. 自我完善 D. 总体国家安全观', 'B. 自我革命');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是国家根本法，是党和人民意志的集中体现，是国家各种制度和法律法规的总依据。', 'A. 法律总纲 B. 民法典 C. 宪法 D. 诉讼法', 'C. 宪法');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“一带一路”建设，坚持（ ）原则，机会和成果属于全世界。', 'A. 互利共赢 B. 共商共建共享 C. 共商共建 D. 平等互惠', 'B. 共商共建共享');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是中国特色社会主义法治体系的理论指导和学理支撑，是全面推进依法治国的行动指南。', 'A. 社会主义制度 B. 社会主义经济 C. 中国特色社会主义法治理论 D. 社会主义法治', 'C. 中国特色社会主义法治理论');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('一百年来，中国共产党团结带领中国人民进行的一切奋斗、一切牺牲、一切创造，归结起来就是一个主题（ ）。', 'A. 建立新中国 B. 追求共同富裕 C. 实现中华民族伟大复兴 D. 实现人民对美好生活的向往', 'C. 实现中华民族伟大复兴');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“四个全面”战略布局中，全面从严治党的核心是（ ）。', 'A. 加强党的长期执政能力建设 B. 提高政府行政效率 C. 推进司法体制改革 D. 扩大公民政治参与', 'A. 加强党的长期执政能力建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国外交的根本保证是（ ）。', 'A. 坚持党对对外工作的集中统一领导 B. 坚持和平发展 C. 坚持合作共赢 D. 坚持独立自主', 'A. 坚持党对对外工作的集中统一领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新发展理念中，绿色发展注重解决的是（ ）。', 'A. 发展动力问题 B. 发展不平衡问题 C. 人与自然和谐共生问题 D. 社会公平正义问题', 'C. 人与自然和谐共生问题');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持系统思维，整体规划育人各个环节，整合利用各种资源，统筹协调各方力量，发挥家庭、学校、社会协同育人机制的作用，实现全员育人、全过程育人、全方位育人，属于着力解决好（ ）的问题。', 'A. 培养什么人 B. 怎样培养人 C. 为谁培养人 D. 谁来培养人', 'B. 怎样培养人');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('信息化、知识经济和创新驱动的时代，（ ）已经成为推动社会发展最活跃、最积极的因素。', 'A. 科技 B. 教育 C. 人才 D. 文化', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的二十大报告指出，全过程人民民主是社会主义民主政治的（ ），是最广泛、最真实、最管用的民主。', 'A. 本质属性 B. 核心内容 C. 内驱动力 D. 具体实践', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的（ ）是党的各级组织和全体党员必须遵守的行为准则，是维护党的团结统一、完成党的任务的保证。', 'A. 章程 B. 纪律 C. 条例 D. 准则', 'B. 纪律');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('社会主义国家是由无产阶级建立和领导的，第一次真正实现了（ ）。', 'A. 党的领导 B. 人民当家作主 C. 民主集中制 D. 人民监督', '人民当家作主');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是军队的根本价值所在。', 'A. 能打仗、打胜仗 B. 听党话、跟党走 C. 作风优良 D. 纪律严明', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('一个国家最基本、最深沉、最持久的力量是（ ）。', 'A. 制度自信 B. 理论自信 C. 道路自信 D. 文化自信', 'D. 文化自信');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平总书记在十九大报告中指出，中国特色社会主义进入新时代，我国社会主要矛盾（ ）。', 'A. 已经转化为人民日益增长的美好生活需要和不平衡不充分的发展之间的矛盾 B. 仍然是无产阶级同资产阶级之间的矛盾 C. 官僚资本同民族资本之间的矛盾 D. 是人民日益增长的物质文化需要同落后的社会生产之间的矛盾', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“黑天鹅”与“灰犀牛”是描述不同类型风险的两个重要概念。关于二者的应对策略，下列说法准确的是（ ）。', 'A. 对于难以预测的“黑天鹅”事件，建立常态化预警机制是最有效的防范手段 B. 对于大概率、可预见的“灰犀牛”事件，应建立常态化预警和防控机制，主动加以防范 C. 区分“黑天鹅”和“灰犀牛”没有实际意义，只需用同一种思维应对即可 D. 应对这两种风险的核心是先发展经济，所有安全问题自然会随之消失', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('在增强党的全面领导能力中，代表我们党坚如磐石、坚不可摧的力量根基是（ ）。', 'A. 群众组织力 B. 思想引领力 C. 社会号召力 D. 政治领导力', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是推进现代化最坚实的根基、最深厚的力量。', 'A. 文化 B. 中国共产党的领导 C. 人民 D. 中华文明', 'C. 人民');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义制度的最大优势是（ ）。', 'A. 共同富裕 B. 不断解放和发展生产力 C. 消灭剥削,消除两极分化 D. 中国共产党领导', 'D. 中国共产党领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('深入推进党自我革命的根本目的是（ ）。', 'A. 巩固党的执政地位 B. 保持党同人民群众的血肉联系 C. 引领社会革命 D. 建设世界上最强大的政党', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('香港回归祖国的时间是（ ）。', 'A. 1978年7月1日 B. 1987年10月1日 C. 1997年7月1日 D. 1997年10月1日', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）一声炮响，使中国先进分子看到了一条崭新的道路，燃起了实现民族独立和人民解放的新希望。', 'A. 五四运动 B. 辛亥革命 C. 新文化运动 D. 十月革命', 'D. 十月革命');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是中国特色社会主义法治体系的根本制度基础，是全面推进依法治国的根本制度保障。', 'A. 中国特色社会主义制度 B. 党的领导 C. 马克思主义指导 D. 以德治国', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是保障和改善民生的工作思路。', 'A. 坚持尽力而为，量力而行 B. 坚守底线、突出重点、完善制度、引领预期 C. 正确把握民生和发展的关系 D. 坚持人人尽责、人人享有', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）最能体现“党的全面领导”的深层逻辑。', 'A. 党领导一切，可以随意干预所有事务 B. 党的领导是为了确保国家发展方向、社会公平和人民根本利益 C. 党的领导只是政治口号，无实际内容 D. 党的领导仅限于党政机关内部', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('到2035年基本实现国防和军队现代化，这一步的关键不包括（ ）。', 'A. 实现军事理论现代化 B. 实现军队组织形态现代化 C. 实现军事人员现代化 D. 实现军事制度现代化', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面依法治国的总目标是（ ）。', 'A. 建设中国特色社会主义法治体系 B. 建设中国特色社会主义法治体系，建设社会主义法治国家 C. 建设社会主义法治国家 D. 有法可依、有法必依、违法必究、执法必严', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是中国特色社会主义最本质的特征。', 'A. 以经济建设为中心 B. 以人为本 C. “五位一体总体布局” D. 中国共产党的领导', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是社会主义的生命，没有民主就没有社会主义。', 'A. 人民民主 B. 人民当家作主 C. 以人民为中心 D. 坚持人民的主体地位', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国式现代化是人口规模巨大的现代化，我国14亿多人口整体迈进现代化社会，规模超过现有发达国家人口的总和，艰巨性和复杂性（ ）。', 'A. 前所未有 B. 可以预见 C. 相对较小 D. 逐步降低', 'A. 前所未有');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('做好人オ工作的重要保障是（ ）。', 'A. 坚持为经济社会发展服务 B. 坚持营造识才爱才敬才用才的环境 C. 坚持深化人才发展体制机制改革 D. 坚持党对人オ工作的全面领导', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是党的政治建设的首要任务。', 'A. 增强“四个意识” B. 贯彻“四个全面” C. 学习贯彻习近平新时代中国特色社会主义思想 D. 保证全党服从中央，维护党中央权威和集中统一领导', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的政治建设是根本性建设，决定党的建设的方向和效果，只有党的政治建设抓好了，党的建设才能夯基固本。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('民主就是指民主选举，不搞“一人一票”竞选就是“不民主”。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('人民军队将在本世纪中叶基本实现国防和军队现代化。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('根据《中华人民共和国国家安全法》，每年的4月10日为全民国家安全教育日。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“五位一体”总体布局中，生态文明建设是根本。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('发挥第三次分配的调节作用，加大税收、社保、转移支付等的调节力度，提高精准性。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我们讲依宪治国、依宪执政，同西方所谓“宪政”有着本质区别，不能把二者混为一谈。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('要在发展过程中始终注重民生、保障民生、改善民生。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('只有党内监督才是全面从严治党的重要方式，群众监督和舆论监督没有实际作用。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义本质上是资本主义的一种形式。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代保障和改善民生，要坚持在发展中保障和改善民生。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('依法治国是党领导人民治理国家的基本方式。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('经济安全与人民群众切身利益关系最密切，是人民群众安全感的晴雨表，是社会安定的风向标', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('凡属重大改革不必于法有据，需要修改法律的可以不用先修改法律，先破后立。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“三个代表”重要思想是当代中国马克思主义、二十一世纪马克思主义，是中华文化和中国精神的时代精华，实现了马克思主义中国化时代化新的飞跃。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义新时代标志着我国已经超越了社会主义初级阶段。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建立健全防范风险机制，主要有（ ）。', 'A. 风险研判机制 B. 决策风险评估机制 C. 风险防控协同机制 D. 风险防控责任机制', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('健全绿色发展的保障体系。统筹各领域资源，打好（ ）的“组合拳”。', 'A. 法治 B. 市场 C. 科技 D. 政策', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平主席关于党的建设的重要思想，包括（ ）。', 'A. 坚持和加强党的全面领导；坚持以党的自我革命引领社会革命；坚持以党的政治建设统领党的建设各项工作 B. 坚持思想建党、理论强党；坚持严密党的组织体系；坚持江山就是人民、人民就是江山 C. 坚持造就忠诚干净担当的高素质干部队伍；坚持聚天下英才而用之 D. 坚持持之以恒正风肃；坚持一体推进不敢腐、不能腐、不想腐', 'A. 坚持和加强党的全面领导；坚持以党的自我革命引领社会革命；坚持以党的政治建设统领党的建设各项工作');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持以人民为中心的发展思想，就要在高质量发展中促进共同富裕，做到（ ）。', 'A. 发展为了人民 B. 发展幸福人民 C. 发展依靠人民 D. 发展成果由人民共享', 'ACD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设更高水平的法治中国，必须（ ）。', 'A. 完善以宪法为核心的中国特色社会主义法律体系 B. 扎实推进依法行政 C. 严格公正司法 D. 加快建设法治社会', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('年春节档，《哪吒之魔童闹海》燃爆大银幕。导演饺子认为，影片成功的关键在于满足了观众对传统题材现代化表达的需求。这启示我们，不断提升中华文化影响力，必须（ ）。', 'A. 推动中华优秀传统文化创造性转化和创新性发展 B. 使中华民族最基本的文化基因同当代中国相适应、同现代社会相协调、同现实文化相融通 C. 把跨越时空、超越国界、富有永恒魅力、具有当代价值的文化精神弘扬起来 D. 加强国际传播能力建设，全面提升国际传播效能', 'ABC');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('加快建设法治中国，必须全面推进（ ）。', 'A. 科学立法 B. 严格执法 C. 公正司法 D. 全民守法', 'A. 科学立法B. 严格执法C. 公正司法D. 全民守法');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持和完善“一国两制”制度体系，要（ ）。', 'A. 加强依法治理相关制度和机制建设 B. 健全中央行使全面管治权的制度 C. 为落实爱国者治理提供制度保障 D. 要继续发展壮大爱国爱港爱澳力量，增强港澳同胞的爱国精神', 'A. 加强依法治理相关制度和机制建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('当今世界正经历百年未有之大变局，具体表现在（ ）。', 'A. 世界多极化、经济全球化、社会信息化、文化多样化深入发展 B. 世界面临的不稳定性不确定性突出，全球性问题加剧 C. 国际力量对比深刻变化，国际体系和国际秩序深度调整 D. 新一轮科技革命和产业变革深入发展', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的领导是做好党和国家各项工作的根本保证，是我国（ ）的根本点，绝对不能有丝毫动摇。', 'A. 民族团结 B. 社会稳定 C. 政治稳定 D. 经济发展', 'C. 政治稳定');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的十八大以来，我们坚持党要管党、全面从严治党，坚持问题导向，以整治“四风”为突破口，“四风”包括:形式主义、（ ）。', 'A. 官僚主义 B. 享乐主义 C. 奢靡之风 D. 利己主义', 'A. 官僚主义B. 享乐主义C. 奢靡之风');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想为解决（ ）、人类文明发展等一系列重大问题提供了新的方向、新的方案、新的选择。', 'A. 世界经济 B. 国际安全 C. 全球治理 D. 社会主义全球化', 'ABC');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想创立的时代背景包括以下（ ）。', 'A. 世界正经历百年未有之大变局 B. 中华民族伟大复兴战略全局 C. 中国特色社会主义进入新时代 D. 中国社会主要矛盾发生转化', 'ABCD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('对共同但有区别的责任原则的理解，正确的说法是（ ）。', 'A. 必须充分考虑历史责任、各国国情和生态治理能力，坚持各尽所能、国家自主决定贡献的制度安排 B. 必须充分肯定发展中国家应对气候变化所作的贡献，照顾其特殊困难和关切 C. 发达国家应该主动承担历史责任，为发展中国家提供资金、技术、能力建设等方面支持 D. 发达国家和发展中国家处于不同发展阶段，但在环境问题上的历史责任相同', 'ABC');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国共产党为什么能，中国特色社会主义为什么好，归根到底是马克思主义行，是（ ）。', 'A. 中国化时代化的马克思主义行 B. 中国式现代化行 C. 中华民族伟大复兴战略行 D. 人类社会发展规律行', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国共产党的根本组织原则和领导制度是（ ）。', 'A. 民主集中制 B. 党的代表大会制度 C. 党的选举制度 D. 党内议事规则', 'A. 民主集中制');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代党的建设总要求中，强调把（ ）贯穿党的各项建设之中。', 'A. 政治建设 B. 思想建设 C. 制度建设 D. 纪律建设', 'A. 政治建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('文化的核心是（ ）。', 'A. 价值观 B. 道德观 C. 历史观 D. 民族观', 'A. 价值观');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('文化自信是更基础、更广泛、更深厚的自信。下列选项中，不属于中国特色社会主义文化自信来源的是（ ）。', 'A. 中华优秀传统文化 B. 革命文化 C. 社会主义先进文化 D. 西方外来文化', 'D. 西方外来文化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('统战工作的关键是要（ ）。', 'A. 坚持求同存异 B. 坚持党的领导 C. 坚持同一性 D. 坚持多样性', 'A. 坚持求同存异');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('科技创新的源头是（ ）。', 'A. 应用研究 B. 基础研究 C. 理论研究 D. 自主创新', 'B. 基础研究');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想的主要创立者是（ ）。', 'A. 习近平 B. 以习近平同志为核心的党中央 C. 以习近平同志为核心的中央军事委员会 D. 以习近平同志为核心的中共中央政治局常委会', 'A. 习近平');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面从严治党，必须加强党的（ ）建设，这是党有效领导国家和社会的重要基础。', 'A. 政治 B. 思想 C. 组织 D. 作风', 'A. 政治');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平指出:“我们党自成立之日起就致力于建设（ ）的新社会，提出了关于未来国家制度的主张，并领导人民为之进行斗争。”', 'A. 文明法治 B. 人民当家作主 C. 人民民主 D. 繁荣发展', 'B. 人民当家作主');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('高质量发展中，“双循环” 新发展格局的战略基点是（ ）。', 'A. 扩大内需 B. 科技创新 C. 对外开放 D. 乡村振兴', 'A. 扩大内需');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的（ ）是党的生命线和根本工作路线，是全面从严治党必须坚守的根本立场。', 'A. 群众路线 B. 思想路线 C. 组织路线 D. 政治路线', 'A. 群众路线');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('社会治理现代化的核心要求是（ ）。', 'A. 政府全面管控 B. 多元主体协同共治 C. 强化法律制裁力度 D. 扩大社会舆论监督', 'B. 多元主体协同共治');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面深化改革必须始终站稳人民立场，坚持（ ）的改革价值取向。', 'A. 以人民为中心 B. 以创新为引领 C. 以发展为中心 D. 以经济建设为中心', 'A. 以人民为中心');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新发展理念中，共享发展注重解决的是（ ）。', 'A. 发展动力问题 B. 发展不平衡问题 C. 人与自然和谐共生问题 D. 社会公平正义问题', 'D. 社会公平正义问题');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是党和人民历经干辛万苦、付出巨大代价取得的根本成就，是实现中华民族伟大复兴的必由之路。', 'A. 改革开放 B. 中国特色社会主义 C. 社会主义现代化 D. 中国式现代化', 'B. 中国特色社会主义');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是国家治理体系和治理能力的重要依托。', 'A. 法治 B. 民主 C. 人民 D. 党的领导', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('下列选项不属于新常态下我国经济发展大势“四个没有变”的是（ ）。', 'A. 经济持续增长的良好支撑基础和条件没有变 B. 经济韧性好、潜力足、回旋余地大的基本特质没有变 C. 经济结构调整优化的前进态势没有变 D. 经济发展平稳的基本面没有变', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平总书记在中央国家安全委员会第一次会议上首次提出总体国家安全观，明确了“五大要素”。以下属于“五大要素”之一且表述准确的是（ ）。', 'A. 以人民安全为根本 B. 以政治安全为宗旨 C. 以经济安全为基础 D. 以促进国际安全为保障', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持以（ ）为底线维护国家主权、安全、发展利益。', 'A. 和平发展 B. 国土完整 C. 互惠互利 D. 国家核心利益', 'D. 国家核心利益');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想创立的时代背景不包括（ ）。', 'A. 世界正经历百年未有之大变局 B. 中华民族伟大复兴战略全局 C. 中国特色社会主义进入新时代 D. 改革开放进入攻坚期和深水区', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设教育强国最重要的基础工作是（ ）。', 'A. 坚定不移推进教育公平 B. 构建全社会共同育人格局 C. 加强教育基础设施建设 D. 加强教师队伍建设', 'D. 加强教师队伍建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('人民民主建立在（ ）基础之上，体现了社会主义国家的性质，反映了社会主义制度的本质要求，是一种新型的社会主义民主。', 'A. 社会主义制度 B. 社会主义经济 C. 人民当家作主 D. 社会主义法治', 'C. 人民当家作主');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）始终是党的生命线和根本工作路线，是我们党永葆青春活力和战斗力的重要传家宝。', 'A. 群众路线 B. 经济路线 C. 人民立场 D. 政治立场', 'A. 群众路线');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('推进中国式现代化需要正确处理好顶层设计与实践探索、战略与策略、守正与创新、效率与公平、活力与秩序、自立自强与对外开放等一系列重大关系。其中，（ ）是前提和基础。', 'A. 顶层设计 B. 实践探索 C. 战略 D. 策略', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('澳门特别行政区享有的自治权有（ ）。', 'A. 行政管理权、立法权、独立的司法权 B. 立法权、司法权 C. 行政管理权、立法权、独立的司法权和终审权 D. 行政管理权、司法权', 'C. 行政管理权、立法权、独立的司法权和终审权');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国社会主义实践后半程的主要历史任务是完善和发展中国特色社会主义制度，为党和国家事业发展、为人民幸福安康、为社会和谐稳定、为国家长治久安提供一整套（ ）的制度体系。', 'A. 更完备、更稳定、更先进 B. 更全面、更稳定、更管用 C. 更全面、更稳定、更先进 D. 更完备、更稳定、更管用', 'D. 更完备、更稳定、更管用');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国始终倡导和坚持（ ），一贯坚持独立自主的和平外交政策，从来都是维护世界和平、促进共同发展的坚定力量。', 'A. 和平共处五项原则 B. 合作共赢 C. 美美与共 D. 和平发展', 'A. 和平共处五项原则');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“两个维护”的内容是（ ）。', 'A. 维护党中央权威和集中统一领导，维护习近平总书记核心地位 B. 维护人民代表大会制度 C. 维护公有制主体地位 D. 维护党内团结', 'A. 维护党中央权威和集中统一领导，维护习近平总书记核心地位');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('以下关于高质量发展的表述中，错误的是（ ）。', 'A. 高质量发展是能够很好满足人民日益增长的美好生活需要的发展 B. 高质量发展是体现新发展理念的发展 C. 高质量发展就是追求GDP高速增长 D. 高质量发展要求实现生产、分配、流通、消费循环通畅', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是中国特色社会主义制度的最大优势，是党和国家各项事业发展的根本政治保证。', 'A. 人民当家作主 B. 全面依法治国 C. 党的领导 D. 坚持走和平发展道路', 'C. 党的领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是坚持和发展中国特色社会主义的行动指南。', 'A. 党的基本路线 B. 党的基本方略 C. 党的基本理论 D. 党的基本原则', 'B. 党的基本理论');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想是中华文化和中国精神的时代精华，主要体现在（ ）。', 'A. 继承和弘扬了中华优秀传统文化 B. 凝练了中国人民在长期奋斗中培育的民族精神 C. 反映了当代中国发展进步的精神需求 D. 以上都是', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('完善社会主义市场经济体制核心问题是处理好（ ）的关系。', 'A. 国家和企业 B. 国家和市场 C. 政府和企业 D. 政府和市场', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我们党立党为公、执政为民的本质要求是（ ）。', 'A. 发展生产力 B. 维护国家安全 C. 为民造福 D. 推进国家治理现代化', 'C. 为民造福');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）直接影响文明的兴衰演替。', 'A. 文化传承与创新 B. 生态环境变化 C. 经济发展 D. 法治建设', 'D. 法治建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面建设社会主义现代化国家，教育是根本，（ ）是关键，人才是基础。', 'A. 科技 B. 人才 C. 创新 D. 共同富裕', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('以（ ）为主线，坚定不移走中国特色解决民族问题的正确道路，坚持和完善民族区域自治制度，加强和改进党的民族工作，全面推进民族团结进步事业。', 'A. 铸牢中华民族共同体意识 B. 深化民族团结进步教育 C. 加强各民族交往交流交融 D. 促进民族团结、共同繁荣', 'A. 铸牢中华民族共同体意识');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('力争到二〇三五年（ ）国防和军队现代化，到本世纪中叶把人民军队（ ）世界一流军队。', 'A. 全面实现；基本建成 B. 全面实现；全面建成 C. 基本实现；基本建成 D. 基本实现；全面建成', 'D. 基本实现；全面建成');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('《中国共产党党章》明确规定，中国共产党是中国工人阶级的先锋队，同时是（ ）。', 'A. 中国人民的先锋队 B. 中华民族的先锋队 C. 中国人民和中华民族的先锋队 D. 中国新阶层的先锋队', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国经济已由高速增长阶段转向高质量发展阶段，正处在转变发展方式、优化经济结构、（ ）的攻关期，建设现代化经济体系是跨越关口的迫切要求和我国发展的战略目标。', 'A. 转换增长动力 B. 优化发展模式 C. 巩固经济地位 D. 细化主攻领域', 'A. 转换增长动力');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面深化改革的总目标是（ ）。', 'A. 坚定道路自信、理论自信、制度自信、文化自信 B. 完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化 C. 建设中国特色社会主义法治体系、建设社会主义法治国家 D. 坚持和发展中国特色社会主义', 'B. 完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新发展理念中，创新发展注重解决的是（ ）。', 'A. 发展动力问题 B. 发展不平衡问题 C. 人与自然和谐共生问题 D. 社会公平正义问题', 'A. 发展动力问题');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('总体国家安全观以（ ）为宗旨。', 'A. 政治安全 B. 人民安全 C. 社会安全 D. 经济安全', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('关注（ ）本身的发展，是社会主义和资本主义的根本区别之一。', 'A. 社会 B. 人 C. 公民 D. 经济', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是人民军队的鲜明特色和政治优势，也是人民军队战无不胜、攻无不克的重要保证。', 'A. 能打胜仗 B. 军民情谊 C. 听党指挥 D. 作风优良', 'D. 作风优良');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ），习近平在中央国家安全委员会第一次会议上首次提出总体国家安全观，强调必须坚持总体国家安全观，走出一条中国特色国家安全道路。', 'A. 2013年5月15日 B. 2014年4月15日 C. 2017年4月15日 D. 2018年5月15日', 'B. 2014年4月15日');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代党和国家事业发展的坚强保证是（ ）。', 'A. 全国一盘棋 B. 人民当家作主 C. 中国共产党的全面领导 D. 以人民为中心', 'C. 中国共产党的全面领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面依法治国的唯一正确道路是（ ）。', 'A. 中国特色社会主义道路 B. 中国特色社会主义政治发展道路 C. 中国特色社会主义法治道路 D. 中国特色社会主义法制道路', 'C. 中国特色社会主义法治道路');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('从全面建设社会主义现代化国家进程的阶段安排看来，到2035年，我国将（ ）。', 'A. 全面建成小康社会 B. 实现中华民族伟大复兴的中国梦 C. 把我国建设成为富强美丽文明和谐的社会现代化强国 D. 基本实现社会主义现代化', 'D. 基本实现社会主义现代化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党内出现管党不力、治党不严的问题具体表现为（ ）个有之。', 'A. 5 B. 6 C. 7 D. 8', 'C. 7');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('维护政权安全，最主要是（ ）。', 'A. 建立强大的军队 B. 坚持和巩固马克思主义在意识形态领域的指导地位 C. 坚持和巩固党的领导和长期执政地位 D. 坚持和巩固人民民主专政', 'C. 坚持和巩固党的领导和长期执政地位');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('发展是改善民生的（ ），我们的发展是以人为本的发展。', 'A. 前提条件 B. 物质保障 C. 基本原则 D. 物质基础', 'D. 物质基础');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）把习近平新时代中国特色社会主义思想确立为党必须长期坚持的指导思想并庄严地写入党章。', 'A. 党的十七大 B. 党的十八大 C. 党的十九大 D. 党的二十大', 'C. 党的十九大');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）通过了关于《中国共产党章程(修正案)》的决议，把习近平新时代中国特色社会主义思想写入党章。', 'A. 党的十七大 B. 党的十八大 C. 党的十九大 D. 党的二十大', 'C. 党的十九大');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('走和平发展道路，就要坚定奉行（ ）的和平外交政策', 'A. 均衡发展 B. 自由开放 C. 独立自主 D. 公平正义', 'C. 独立自主');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('信息化、知识经济和创新驱动的时代,推动社会发展最活跃、最积极的因素是（ ）。', 'A. 科技 B. 政策 C. 人才 D. 信息', 'C. 人才');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是指民主的制度安排，实质民主是指民主始终追求的价值目标，二者有机结合。', 'A. 程序民主 B. 协商民主 C. 人民民主 D. 全过程人民民主', 'A. 程序民主');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('阅读材料，回答问题: 材料一 食品标签，在生活中很常见，有时又“难看见”。消费者好不容易在食品包装上找到了标签中“生产日期”那一行，发现还需要“见包装喷码处”，翻了一圈找到了“喷码处”，又正好是包装拼接的地方。数字喷码要么太小，要么不清晰，经过仔细辨认知道了生产日期，还要再回头去找“保质期”。如此反复，才能搞清楚食品是否还在保质期内。 现实生活中，各类食品包装形状、材质不同，生产日期和保质期标注的位置也不统一，有的不易查找。有商家甚至通过缩小字体、色彩掩盖等方式，故意让消费者“忽视”保质期等重要信息，误导消费。这样的行为侵犯了消费者合法权益。 ——林丽鹂：《让食品“小标签”发挥大作用》，《人民日报》，2024年05月15日05版 材料二 《中华人民共和国消费者权益保护法实施条例》自2024年7月1日起施行。《条例》第九条规定经营者应当采用通俗易懂的方式，真实、全面地向消费者提供商品或者服务相关信息，不得通过虚构经营者资质、资格或者所获荣誉，虚构商品或者服务交易信息、经营数据，篡改、编造、隐匿用户评价等方式，进行虚假或者引人误解的宣传，欺骗、误导消费者。 ——《中华人民共和国国务院令第778号》，中华人民共和国中央人民政府网，2024年03月15日', '', '[1. 完善法律法规，细化食品标签标注规范，明确生产日期、保质期等信息的标注位置、字体大小、清晰度等要求。
2. 加强执法监管，市场监管部门应定期检查食品标签合规情况，对违规企业依法处罚。
3. 推进全民守法，通过宣传教育提高消费者维权意识，鼓励消费者依法举报标签不规范行为。, 从食品企业经营者角度：应严格遵守《消费者权益保护法实施条例》等法律法规，真实、全面标注食品标签信息，不故意缩小字体、色彩掩盖，保障消费者知情权。
从公民角度：应增强法治意识，学法懂法用法，购买食品时仔细查看标签，发现不规范标注依法向有关部门投诉举报，维护自身合法权益。]');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('人民代表大会制度是我国的根本领导制度。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国式现代化创造了人类文明新形态，为人类实现现代化提供了新的选择。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色大国外交牢牢把握服务民族振兴、促进人类进步这条主线。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('保障和改善民生的重要原则是只要尽力而为，不要量力而行。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('构建新发展格局最本质的特征是实现高水平自立自强。', 'A. 对 B. 错', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持党对人民军队的绝对领导是人民军队能打仗、打胜仗的军事战略指导。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('把教育技术掌握在自己手中，才能真正掌握竞争和发展的主动权。', 'A. 对 B. 错', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设生态文明是顺应人类文明进程.实现人与自然和谐共生的必然要求，具有历史必然性。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国共产党领导是中国特色社会主义最本质的特征。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('民主的评价标准是单一的，只有“一人一票”竞选才是民主。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持党对人民军队的绝对领导，是马克思主义建党建军的一条基本原则。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('创新创造是文化的生命所在，是文化的本质特征。', 'A. 对 B. 错', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持党对人民军队的绝对领导必须有一整套制度作保证。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面深化改革不需要兼顾效率与公平，只需注重经济发展速度即可。', 'A. 对 B. 错', 'B. 错');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国要在总结实践经验的基础上，丰富和发展对外工作理念，使我国对外工作有鲜明的中国特色、中国风格、中国气派。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全过程人民民主是社会主义民主政治的本质属性。', 'A. 对 B. 错', 'A. 对');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('中国特色社会主义是历史和人民的选择，这一论断的依据包括（ ）。', 'A. 它是在改革开放40多年的伟大实践中走出来的 B. 它是在中华人民共和国成立70多年的持续探索中走出来的 C. 它是在对近代以来180多年中华民族发展历程的深刻总结中走出来的 D. 它是在对中华民族5000多年悠久文明的传承中走出来的', 'A、B、C、D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是我们解决台湾问题的最大底气。', 'A. 中国特色社会主义事业取得的伟大成就 B. 我国经济、科技、国防实力的持续增强 C. 包括台湾人民在内的全国各族人民万众一心、同仇敌忾 D. 国际社会支持', 'ABC');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('到2035年，基本实现国防和军队现代化，这一步的关键是实现（ ）。', 'A. 军事理论现代化 B. 军队组织形态现代化 C. 军事人员现代化 D. 武器装备现代化', 'A. 军事理论现代化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('人民代表大会制度是坚持（ ）有机统一的根本政治制度安排。', 'A. 党的领导 B. 全面深化改革 C. 人民当家作主 D. 依法治国', 'A、C、D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平总书记指出:“当代中国共产党人和中国人民应该而且一定能够担负起新的文化使命，在实践创造中进行文化创造，在历史进步中实现文化进步!”新时代新的文化使命是（ ）。', 'A. 在新的起点上继续推动文化繁荣 B. 建设文化强国 C. 建设中华民族现代文明 D. 传承发展中华传统文化', 'A. 在新的起点上继续推动文化繁荣');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('民生工作离老百姓最近，同老百姓生活最密切，（ ）是我们的第一要务。', 'A. 解决发展问题 B. 解决贫困问题 C. 改善民生 D. 改善生活', 'C. 改善民生');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的二十大报告指出，中国共产党立志于中华民族千秋伟业，致力于人类和平与发展崇高事业，全党同志要始终牢记“三个务必”，这“三个务必”是（ ）。', 'A. 务必不忘初心、牢记使命 B. 务必谦虚谨慎、艰苦奋斗 C. 务必贯彻好群众路线 D. 务必敢于斗争、善于斗争', 'A. 务必不忘初心、牢记使命  
B. 务必谦虚谨慎、艰苦奋斗  
D. 务必敢于斗争、善于斗争');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持马克思主义在意识形态领域指导地位的根本制度，是（ ）的必然要求。', 'A. 高质量发展 B. 坚持和巩固我国社会主义制度 C. 保证我国文化建设正确方向 D. 全面依法治国', 'B. 坚持和巩固我国社会主义制度');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想创立的时代背景是（ ）。', 'A. 世界百年未有之大变局加速演进 B. 新时代中国正处于中华民族伟大复兴的关键时期 C. 我国经济高速度发展 D. 中国成为世界领导角色', 'AB');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('推动高质量发展具有的重大战略意义包括（ ）。', 'A. 为全面建设社会主义现代化国家提供更为坚实的物质基础 B. 是不断满足人民对美好生活需要的重要保证 C. 是维护国家长治久安的必然要求 D. 是我国经济发展必须追求的唯一目标', 'ABC');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('维护党中央权威和集中统一领导，最关键的是坚决维护（ ）。', 'A. 人民群众的核心地位 B. 习近平同志党中央的核心 C. 行政机关的核心地位 D. 习近平同志全党的核心地位', 'BD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('加快建设教育强国、科技强国、人才强国，坚持（ ）。', 'A. 教育是全面建设社会主义现代化国家的坚实基础 B. 科技是全面建设社会主义现代化国家的强大动力 C. 人才是全面建设社会主义现代化国家的有力支撑 D. 科技是全面建设社会主义现代化国家的坚实基础', 'ABC');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('确保党始终总揽全局、协调各方，必须增强政治意识（ ），自觉维护党中央权威和集中统一领导，自觉在思想上政治上行动上同党中央保持高度一致。', 'A. 大局意识 B. 核心意识 C. 中心意识 D. 看齐意识', 'ABD');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设社会主义文化强国、推动社会主义文化繁荣兴盛，关键在于（ ）。', 'A. 坚定中国特色社会主义文化自信 B. 高质量发展 C. 提高综合国力 D. 贯彻新发展理念', 'A. 坚定中国特色社会主义文化自信');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的十九届四中全会第一次从（ ）、分配制度、资源配置方式等方面阐述了我国基本经济制度的内涵，把我们党对社会主义基本经济制度的认识提高到一个新境界。', 'A. 经济特点 B. 发展模式 C. 所有制结构 D. 生产力水平', 'C. 所有制结构');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）就是形成以保障基本生活为主的社会公平保障体系，织牢民生安全网的“网底”，对困难群众实行应保尽保。', 'A. 坚守底线 B. 突出重点 C. 完善制度 D. 引导预期', 'A. 坚守底线');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('邓小平指出:“社会主义最大的优越性就是（ ），这是体现社会主义本质的一个东西。”', 'A. 党的领导 B. 共同富裕 C. 办事效率高 D. 走和平发展道路', 'B. 共同富裕');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平总书记在党的十八届四中全会第二次全体会议上强调，历史是最好的老师。经验和教训使我们党深刻认识到，（ ）是治国理政不可或缺的重要手段。', 'A. 法治 B. 政策 C. 道德 D. 公正', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('2022年4月，习近平在（ ）上提出全球安全倡议。', 'A. 博鳌亚洲论坛年会 B. 世界经济论坛年会 C. 金砖国家领导人峰会 D. “二十国”集团峰会', 'A. 博鳌亚洲论坛年会');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面依法治国必须抓住领导干部这个（ ）。', 'A. “关键少数” B. “关键力量” C. “关键核心” D. “关键主体”', 'A. “关键少数”');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('维护意识形态安全，最主要是（ ）。', 'A. 落实意识形态工作责任制 B. 把意识形态工作的领导权、管理权、话语权牢牢掌握在党的手中 C. 及时掌握意识形态形势和动态 D. 坚持和巩固马克思主义在意识形态领域的指导地位', 'D');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是我们党的生命线和根本工作路线，是我们党永葆青春活力和战斗力的重要传家宝。', 'A. 武装斗争 B. 群众路线 C. 统一战线 D. 党的领导', 'B. 群众路线');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是意识形态工作的主阵地、主战场、最前沿。', 'A. 互联网 B. 学校 C. 新闻出版 D. 传统媒体', 'A. 互联网');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代中国共产党深刻把握推进共同富裕规律，提出“要深入研究不同阶段的目标，分阶段促进共同富裕：到（ ），全体人民共同富裕取得更为明显的实质性进展，基本公共服务实现均等化”。', 'A. 中国共产党成立一百年 B. “十四五”末 C. 2035年 D. 本世纪中叶', 'C. 2035年');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代坚持和发展中国特色社会主义的根本立场是（ ）。', 'A. 坚持党的领导 B. 坚持以人民为中心 C. 坚持全面深化改革 D. 坚持新发展理念', 'B. 坚持以人民为中心');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('经济社会发展和国家现代化的基本规律是（ ）。', 'A. 创新驱动发展 B. 科技自立自强 C. 人才引领驱动 D. 教育优先发展', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('建设中国特色社会主义法治体系，必须坚持立法先行，抓住提高（ ）这个关键。', 'A. 立法规则 B. 立法数量 C. 立法原则 D. 立法质量', 'D. 立法质量');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持以人民为中心的发展思想，在高质量发展中促进共同富裕，正确处理（ ）的关系，构建初次分配、再分配、三次分配协调配套的基础性制度安排。', 'A. 效率和公平 B. 收入和分配 C. 经济和社会 D. 政府和市场', 'A. 效率和公平');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面深化改革要坚持（ ）是解放和发展社会生产力、解放和增强社会活力的总开关。', 'A. 实事求是 B. 解放思想 C. 开拓创新 D. 贯彻新发展理念', 'B. 解放思想');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是社会文明进步的基础，是民族昌盛和国家富强的重要标志，是促进人的全面发展的必然要求。', 'A. 改善民生 B. 社会保障体系 C. 人民健康 D. 就业', 'C. 人民健康');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('要坚定维护以（ ）为核心的国际体系、以国际法为基础的国际秩序，维护和巩固第二次世界大战胜利成果，积极维护开放型世界经济体制，加强国际社会应对全球性挑战的能力。', 'A. 本国 B. 联合国 C. 西方发达国家 D. 发展中国家', 'B. 联合国');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我们党的最大政治优势是（ ）。', 'A. 党领导一切 B. 走中国特色社会主义道路 C. 人多力量大 D. 密切联系群众', 'D. 密切联系群众');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代党的组织路线强调，以（ ）为重点，着力培养忠诚干净担当的高素质干部。', 'A. 组织体系建设 B. 干部队伍建设 C. 人才队伍建设 D. 党员队伍建设', 'A. 组织体系建设');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('党的十八届三中全会作出了全面深化改革的决定，把（ ）确定为全面深化改革的总目标。', 'A. 完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化 B. 完善和发展科学执政和民主执政水平、推进国家治理体系现代化 C. 完善和发展依法执政和民主执政水平、推进国家治理能力现代化 D. 完善和发展中国特色社会主义理论、推进国家治理能力现代化', 'A. 完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我国国家制度和国家治理体系具有多方面的显著优势，其中最大优势是（ ）。', 'A. 全国一盘棋 B. 人民当家作主 C. 中国共产党领导 D. 以人民为中心', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('社会主要矛盾的变化要求我们必须坚持以（ ）为中心的发展思想。', 'A. 经济建设 B. 人民 C. 科技创新 D. 生态保护', 'B. 人民');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('培育和践行社会主义核心价值观，要把（ ）融入社会生活各个方面。', 'A. 社会主义核心价值体系 B. 理想信念、价值理念、道德观念 C. 中华优秀传统文化 D. 社会主义核心价值观', 'D. 社会主义核心价值观');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是统一战线最核心、最根本的问题。', 'A. 大团结大联合 B. 广交朋友 C. 凝聚人心 D. 坚持党的领导', 'D. 坚持党的领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是我国的根本政治制度，是符合我国国情和实际、体现社会主义国家性质、保证人民当家作主、保障实现中华民族伟大复兴的好制度，是我们党领导人民在人类政治制度史上的伟大创造。', 'A. 区域自治制度 B. 民主集中制 C. 人民代表大会制度 D. 政治协商制度', 'C. 人民代表大会制度');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持以人民为中心，在推动社会全面进步中促进（ ）全面发展。', 'A. 人 B. 经济 C. 政治 D. 文化', 'A. 人');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平强调在坚持“第一个结合”的基础上，明确提出“第二个结合”就是把马克思主义基本原理同（ ）相结合。', 'A. 人才培养 B. 科技创新 C. 中华优秀传统文化 D. 对外开放', 'C. 中华优秀传统文化');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是新时代坚持和发展中国特色社会主义的政治保证。', 'A. 全面深化改革开放 B. 坚持中国共产党领导 C. 坚持以人民为中心 D. 坚定不移全面从严治党', 'B');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('新时代坚持和发展中国特色社会主义的根本动力是（ ）。', 'A. 全面深化对外开放 B. 全面深化改革 C. 全面深化经济体制改革 D. 全面深化政治体制改革', 'B. 全面深化改革');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('国家安全工作，归根结底是保障（ ），为群众安居乐业提供坚强保障。有了安全感，获得感才有保障，幸福感才会持久。', 'A. 人民利益 B. 社会稳定 C. 经济发展 D. 领土完整', 'A. 人民利益');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）明确提出形成中国特色社会主义法律体系的重大任务。', 'A. 党的十五大 B. 党的十八大 C. 党的十九届六中全会 D. 党的二十大', 'A. 党的十五大');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('引领全球治理体系改革应坚持的理念是（ ）。', 'A. 人权 B. 维护国家核心利益 C. 公平正义 D. 开放有序', 'C. 公平正义');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ），是检验更高水平的平安中国建设成效的重要标志。', 'A. 人民生活水平提升 B. 社会治理能力现代化 C. 社会更加安全稳定有序 D. 共同富裕', 'C. 社会更加安全稳定有序');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ），习近平在第七十六届联合国大会上提出全球发展倡议。', 'A. 2019年8月 B. 2020年7月 C. 2021年9月 D. 2022年6月', 'C. 2021年9月');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('坚持人才强军，必须（ ）。', 'A. 实施新时代人才强军战略，锻造德才兼备的高素质、专业化新型军事人才 B. 培养有灵魂、有本事、有血性、有品德的新时代革命军人 C. 锻造具有铁一般信仰、铁一般信念、铁一般纪律、铁一般担当的过硬部队 D. 按照法治要求转变治军方式，实现从单纯依靠行政命令的做法向依法行政的根本性转变', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('总体国家安全观以（ ）为基础，加强经济安全风险预警、防控机制和能力建设。', 'A. 国土安全 B. 经济安全 C. 国内安全 D. 国际安全', 'B. 经济安全');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('面对波谲云诡的国际形势、复杂敏感的周边环境、艰巨繁重的改革发展稳定任务，我们必须树立（ ）。', 'A. 忧患意识 B. 零和思维 C. 底线思维 D. 全局意识', 'A. 忧患意识');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平新时代中国特色社会主义思想的内在精神特质是（ ）。', 'A. 人民至上 B. 自信自立 C. 守正创新 D. 问题导向', 'C');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面依法治国的总抓手是（ ）。', 'A. 建设中国特色社会主义法治体系，建设社会主义法治国家 B. 建设中国特色社会主义法治体系 C. 建设社会主义法治国家 D. 坚持中国共产党的领导', 'B. 建设中国特色社会主义法治体系');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平强军思想明确（ ）是人民军队建军之本、强军之魂。', 'A. 政治工作 B. 党对人民军队的绝对领导 C. 练兵备战 D. 先进科技', 'B. 党对人民军队的绝对领导');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('在网络统战工作方面，要把（ ）结合起来，走好网络群众路线，支持网络人士为维护意识形态安全发挥正能量。', 'A. “面对面”和“键对键” B. “面对面”和“线对线” C. “网对网”和“线对线” D. “键对键”和“线对线”', 'A. “面对面”和“键对键”');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是全面建设社会主义现代化国家的强大动力', 'A. 科技 B. 教育 C. 人才 D. 创新', 'D. 创新');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ），这是实现祖国统一的战略思路。', 'A. 坚持“和平统一、一国两制”基本方针 B. 坚持一个中国原则和“九二共识” C. 坚持推动两岸关系融合发展 D. 坚持在祖国大陆发展进步基础上解决台湾问题', 'A. 坚持“和平统一、一国两制”基本方针');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('我们坚决反对任何国家以任何借口干涉（ ）事务，这是国际社会公认的准则。', 'A. 香港、澳门和台湾 B. 周边国家 C. 欧洲国家 D. 美洲国家', 'A');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('一体推进“三不腐”机制中，“不想腐”的关键是（ ）。', 'A. 强化不敢腐的震慑 B. 扎牢不能腐的笼子 C. 增强不想腐的自觉 D. 加强不能腐的制度', 'C. 增强不想腐的自觉');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('“一国两制”的根本宗旨是（ ）。', 'A. 保持香港、澳门长期繁荣稳定 B. 解决台湾问题 C. 维护国家主权、安全、发展利益，保持香港、澳门长期繁荣稳定 D. 实现中华民族伟大复兴', 'C. 维护国家主权、安全、发展利益，保持香港、澳门长期繁荣稳定');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平在（ ）报告中进一步强调“打铁必须自身硬”，充分表明我们党坚持刀刃向内的非凡勇气和高度清醒。', 'A. 党的十八届三中全会 B. 党的十九大 C. 党的十九届六中全会 D. 党的二十大', 'B. 党的十九大');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('全面从严治党必须把（ ）挺在前面，纪严于法、纪在法前，这是全面从严治党的治本之策。', 'A. 纪律 B. 法律 C. 道德 D. 制度', 'A. 纪律');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('习近平总书记指出，中国特色社会主义是社会主义，不是别的什么主义。这一论断的核心依据是中国特色社会主义坚持了（ ）。', 'A. 资本主义市场经济体制 B. 马克思主义关于科学社会主义的基本原则 C. 西方议会民主制度 D. 多党轮流执政模式', 'B. 马克思主义关于科学社会主义的基本原则');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('检验我们一切工作的最高标准是（ ）。', 'A. 经济发展水平 B. 综合国力提升 C. 人民拥护不拥护、赞成不赞成、高兴不高兴、答应不答应 D. 社会稳定程度', 'C. 人民拥护不拥护、赞成不赞成、高兴不高兴、答应不答应');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('提出构建人类命运共同体重大理念，提出共建“一带一路”倡议，提出全球发展倡议、全球安全倡议、全球文明倡议，深刻回答（ ）的时代课题。', 'A. “共建人类家园” B. “什么是人类命运共同体” C. “人类向何处去” D. “世界怎么了、我们怎么办”', 'D. “世界怎么了、我们怎么办”');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('完善和发展中国特色社会主义制度、推进国家治理体系和治理能力现代化。后一句规定了（ ）。', 'A. 在根本方向指引下完善和发展中国特色社会主义制度的鲜明指向 B. 全面深化改革的根本方向 C. 全面深化改革的主要目的 D. 全面深化改革的出发点和落脚点', 'A. 在根本方向指引下完善和发展中国特色社会主义制度的鲜明指向');
INSERT OR IGNORE INTO answers (title, options, answer) VALUES ('（ ）是人民当家作主和依法治国的根本保证。', 'A. 人民民主 B. 党的领导 C. 宪法 D. 全过程民主', 'B. 党的领导');
